export const ShopActionTypes = {
    FETCH_COLLECTION_SUCESS: 'FETCH_COLLECTION_SUCESS',
    FETCH_COLLECTION_FAILED: 'FETCH_COLLECTION_FAILED',
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START' 
}