const UserActionTypes = {
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    SIGNIN_SUCESS: "SIGNIN_SUCESS",
    SIGNIN_FAILURE: "GOOGLE_SIGNIN_FAILURE",
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCESS: 'SIGN_OUT_SUCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCESS: 'SIGN_UP_SUCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
};

export default UserActionTypes;